i2c:
  sda: 
    number: ${i2c_sda}
  scl:
    number: ${i2c_scl}
  id: i2c0
  scan: True

sensor:
  - platform: bh1750
    name: "BH1750 Illuminance"
    id: bh1750_lux
    address: 0x23
    update_interval: 1s
