sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    id: internal_temperature

text_sensor:
  - platform: version
    name: "ESPHome Version"
    id: esphome_version

button:
  - platform: restart
    name: "Restart Device"
