debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    reset_reason:
      name: "Reset Reason"
    device:
      name: "Device Info"
sensor:
  - platform: debug
    free:
      name: "Heap Free"
      internal: True
    block:
      name: "Heap Max Block"
      internal: True
    #psram:
    #  name: "Free PSRAM"
    #  internal: True
