debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    id: debug_text_sensor
    reset_reason:
      name: "Reset Reason"
sensor:
  - platform: debug
    id: debug_sensor
    free:
      name: "Heap Free"
      internal: True
    block:
      name: "Heap Max Block"
      internal: True
    #psram:
    #  name: "Free PSRAM"
    #  internal: True
