substitutions:
  glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/\\[]|&@#'"

font:
  # Light 300
  # Regular 400
  # Medium 500 
  # SemiBold 600
  # Bold 700
  # ExtraBold 800 

  - file: "gfonts://Lato@400"
    glyphs: ${glyphs}
    size: 12
    bpp: 4
    id: arial_12
  - file: "gfonts://Lato@400"
    glyphs: ${glyphs}
    size: 14
    bpp: 4
    id: arial_14
  - file: "gfonts://Lato@400"
    glyphs: ${glyphs}
    size: 16
    bpp: 4
    id: arial_16
  - file: "gfonts://Lato@700"
    glyphs: ${glyphs}
    size: 16
    bpp: 4
    id: arial_bold_16
  - file: "gfonts://Lato@400"
    glyphs: ${glyphs}
    size: 20
    bpp: 4
    id: arial_20
  - file: "gfonts://Lato@700"
    glyphs: ${glyphs}
    bpp: 4
    size: 20
    id: arial_bold_20

  - file: "gfonts://B612@400"
    glyphs: ${glyphs}
    size: 12
    id: b612_12
  - file: "gfonts://B612@400"
    glyphs: ${glyphs}
    size: 14
    id: b612_14
  - file: "gfonts://B612@400"
    glyphs: ${glyphs}
    size: 16
    id: b612_16
  - file: "gfonts://B612@700"
    glyphs: ${glyphs}
    size: 16
    id: b612_bold_16
