i2c:
  sda: 
    number: ${i2c_sda}
  scl:
    number: ${i2c_scl}
  scan: True

# I2C address 0x40 or 0x41
sensor:
  - platform: htu31d
    temperature:
      name: "HTU31D Temp"
      id: htu31d_temp
      filters:
        - lambda: return x + htu31d_temp_offset->state;
    humidity:
      name: "HTU31D Humid"
      id: htu31d_humid
      filters:
        - lambda: return x + htu31d_humid_offset->state;
    update_interval: 60s    #default

number:
  - platform: template
    id: htu31d_temp_offset
    name: "HTU31D T Offset"
    unit_of_measurement: "°C"
    entity_category: config
    optimistic: true
    step: 0.5
    min_value: -5
    max_value: 5
    restore_value: true
    initial_value: 0.0
    mode: box
  - platform: template
    id: htu31d_humid_offset
    name: "HTU31D RH Offset"
    unit_of_measurement: "%"
    entity_category: config
    optimistic: true
    step: 1.0
    min_value: -15
    max_value: 15
    restore_value: true
    initial_value: 0.0
    mode: box
    
