i2c:
  sda: 
    number: ${i2c_sda}
  scl:
    number: ${i2c_scl}
  id: i2c0
  scan: True

sensor:
  - platform: sht3xd
    id: sht3xd_sensor
    temperature:
      name: "SHT3X Temp"
      id: sht3x_temp
      filters:
        - lambda: return x + sht3x_temp_offset->state;
    humidity:
      name: "SHT3X Humid"
      id: sht3x_humid
      filters:
        - lambda: return x + sht3x_humid_offset->state;
    address: 0x44           # default. Might be 0x45
    update_interval: 60s    # default

number:
  - platform: template
    id: sht3x_temp_offset
    name: "SHT3X T Offset"
    unit_of_measurement: "°C"
    entity_category: config
    optimistic: true
    step: 0.5
    min_value: -5
    max_value: 5
    restore_value: true
    initial_value: 0.0
    mode: box
  - platform: template
    id: sht3x_humid_offset
    name: "SHT3X RH Offset"
    unit_of_measurement: "%"
    entity_category: config
    optimistic: true
    step: 1.0
    min_value: -15
    max_value: 15
    restore_value: true
    initial_value: 0.0
    mode: box

