i2c:
  sda: 
    number: ${i2c_sda}
  scl:
    number: ${i2c_scl}
  scan: True

sensor:
  - platform: sht4x
    temperature:
      name: "SHT4X Temp"
      id: sht4x_temp
      filters:
        - lambda: return x + sht4x_temp_offset->state;
    humidity:
      name: "SHT4X Humid"
      id: sht4x_humid
      filters:
        - lambda: return x + sht4x_humid_offset->state;
    precision: "High"       # default
    heater_max_duty: 0.0    # defalut max 0.05
    heater_power: "High"    # default
    heater_time: "Long"     # default or "Short"
    update_interval: 60s    # default
    address: 0x44           # default, might be 0x45

number:
  - platform: template
    id: sht4x_temp_offset
    name: "SHT4X T Offset"
    unit_of_measurement: "°C"
    entity_category: config
    optimistic: true
    step: 0.5
    min_value: -5
    max_value: 5
    mode: box
    restore_value: true
    initial_value: 0.0
  - platform: template
    id: sht4x_humid_offset
    name: "SHT4X RH Offset"
    unit_of_measurement: "%"
    entity_category: config
    optimistic: true
    step: 1.0
    min_value: -15
    max_value: 15
    mode: box
    restore_value: true
    initial_value: 0.0


