sensor:
  - platform: uptime
    name: Uptime Sensor
    id: dev_uptime
    update_interval: 1s
    internal: True

text_sensor:
  - platform: uptime
    name: "Uptime Formatted"
    id: uptime_formatted
    update_interval: 1s
